# Generated by Django 3.0.5 on 2024-05-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=30, help_text='Duration in minutes'),
            preserve_default=False,
        ),
    ]
